In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel(r'C:\Users\koreshilova_ea\Desktop\_Эксперименты_.xlsx').replace(0, np.nan)

In [3]:
data

,name,1.1,1.2,1.3,1.4,1.5,1.6,1.8,1.9,1.10,...,3.6,3.8,3.9,3.10,3.11,3.12,3.13,3.14,3.15,3.16
0,Башурова София Александровна,7.0,6.0,6.0,5.0,7.0,4.0,7.0,7.0,6.0,...,7.0,7.0,6.0,7.0,6.0,6.0,1.0,7.0,3.0,5.0
1,Волохова Юлия Дмитриевна,6.0,6.0,5.0,5.0,3.0,6.0,4.0,7.0,6.0,...,7.0,7.0,7.0,7.0,6.0,2.0,2.0,7.0,2.0,1.0
2,Высоцкая Дарья Игоревна,5.0,4.0,4.0,4.0,6.0,3.0,6.0,5.0,3.0,...,4.0,6.0,7.0,4.0,5.0,7.0,NaN,4.0,6.0,4.0
3,Дружинина Виктория Андреевна,5.0,4.0,5.0,2.0,6.0,5.0,6.0,3.0,5.0,...,4.0,2.0,3.0,5.0,4.0,3.0,2.0,6.0,6.0,5.0
4,Завгородний Фёдор Денисович,6.0,4.0,5.0,5.0,2.0,7.0,2.0,5.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Камышенко Александра Сергеевна,4.0,7.0,7.0,1.0,1.0,3.0,2.0,6.0,7.0,...,3.0,4.0,6.0,6.0,7.0,1.0,6.0,6.0,7.0,6.0
6,Карюхина Вероника Эдуардовна,3.0,4.0,4.0,6.0,2.0,3.0,2.0,4.0,5.0,...,5.0,4.0,5.0,5.0,6.0,6.0,4.0,5.0,5.0,4.0
7,Конева Эльза Дмитриевна,5.0,4.0,4.0,6.0,6.0,3.0,7.0,5.0,4.0,...,7.0,7.0,6.0,3.0,5.0,4.0,4.0,6.0,6.0,6.0
8,Кравченко Николай Андреевич,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Кудымова Мария Андреевна,1.0,6.0,7.0,4.0,7.0,7.0,7.0,7.0,7.0,...,4.0,7.0,6.0,4.0,7.0,4.0,1.0,6.0,3.0,3.0
10,Кутний Ксения Владимировна,3.0,6.0,5.0,3.0,2.0,3.0,6.0,1.0,1.0,...,5.0,7.0,5.0,5.0,5.0,3.0,2.0,2.0,4.0,6.0
11,Мурашова Варвара Дмитриевна,5.0,5.0,3.0,6.0,7.0,2.0,4.0,4.0,3.0,...,4.0,2.0,5.0,4.0,3.0,5.0,5.0,5.0,6.0,6.0
12,Овеян Анна Микаеловна,5.0,4.0,6.0,6.0,7.0,5.0,7.0,7.0,3.0,...,3.0,7.0,7.0,4.0,5.0,5.0,6.0,5.0,5.0,5.0
13,Скворцов Артём Максимович,6.0,4.0,6.0,3.0,6.0,5.0,6.0,3.0,3.0,...,4.0,4.0,5.0,3.0,6.0,3.0,6.0,5.0,6.0,6.0
14,Фокеева Ирина Евгеньевна,5.0,4.0,3.0,4.0,7.0,4.0,2.0,4.0,4.0,...,5.0,7.0,7.0,4.0,5.0,5.0,2.0,5.0,3.0,3.0
15,Яр Алена,7.0,7.0,1.0,1.0,3.0,7.0,7.0,2.0,4.0,...,5.0,2.0,5.0,6.0,5.0,6.0,5.0,3.0,4.0,3.0

In [4]:
group_1 = data[[col for col in data.columns if col.startswith('1')]]
group_2 = data[[col for col in data.columns if col.startswith('2')]]
group_3 = data[[col for col in data.columns if col.startswith('3')]]

In [5]:
# Построчное сравнение значений
comparison_results = pd.DataFrame()

# for index, row in data.iterrows():
#     row_group_1 = row[group_1.columns].values
#     row_group_2 = row[group_2.columns].values
#     row_group_3 = row[group_3.columns].values

#     # Сравнение: группа 1 > группа 2
#     comparison_results.loc[index, 'group_1_vs_group_2'] = all(row_group_1 <= row_group_2)

#     # Сравнение: группа 1 > группа 3
#     comparison_results.loc[index, 'group_1_vs_group_3'] = all(row_group_1 <= row_group_3)

#     # Сравнение: группа 2 > группа 3
#     comparison_results.loc[index, 'group_2_vs_group_3'] = all(row_group_2 <= row_group_3)

# print(comparison_results)

In [6]:
comparison_results['mean_group_1'] = round(group_1.mean(axis=1), 2)
comparison_results['mean_group_2'] = round(group_2.mean(axis=1), 2)
comparison_results['mean_group_3'] = round(group_3.mean(axis=1), 2)

In [7]:
comparison_results

    mean_group_1  mean_group_2  mean_group_3
0           5.60          5.13          5.73
1           4.73          5.07          5.07
2           4.60          4.60          5.29
3           4.47           NaN          4.20
4           4.20          5.60           NaN
5           4.67          4.67          5.13
6           4.20          4.93          4.80
7           4.73          5.27          5.47
8            NaN          5.67           NaN
9           5.27          5.47          4.60
10          3.33          4.40          4.33
11          4.80          4.67          4.60
12          5.00          5.53          5.27
13          4.80           NaN          5.07
14          4.33          4.53          4.73
15          3.67          4.67          4.47

In [8]:
comparison_results['%_mean_gr_1_and_gr_2'] = round(((comparison_results['mean_group_2'] - comparison_results['mean_group_1'])) / comparison_results['mean_group_1'] * 100, 2)
comparison_results['%_mean_gr_2_and_gr_3'] = round(((comparison_results['mean_group_3'] - comparison_results['mean_group_2'])) / comparison_results['mean_group_2'] * 100, 2)
comparison_results['%_mean_gr_1_and_gr_3'] = round(((comparison_results['mean_group_3'] - comparison_results['mean_group_1'])) / comparison_results['mean_group_1'] * 100, 2)

In [9]:
groups = {
    'behavior_group_1': ['1.1', '1.5', '1.8'],
    'behavior_group_2': ['2.1', '2.5', '2.8'],
    'behavior_group_3': ['3.1', '3.5', '3.8']
}

for group_name, columns in groups.items():
    comparison_results[group_name] = round(data[columns].mean(axis=1), 2)

In [10]:
comparison_results['%_behavior_gr_1_and_gr_2'] = round(((comparison_results['behavior_group_2'] - comparison_results['behavior_group_1'])) / comparison_results['behavior_group_1'] * 100, 2)
comparison_results['%_behavior_gr_1_and_gr_3'] = round(((comparison_results['behavior_group_3'] - comparison_results['behavior_group_1'])) / comparison_results['behavior_group_1'] * 100, 2)
comparison_results['%_behavior_gr_2_and_gr_3'] = round(((comparison_results['behavior_group_3'] - comparison_results['behavior_group_2'])) / comparison_results['behavior_group_2'] * 100, 2)

In [11]:
groups = {
    'sub_norm_group_1': ['1.2', '1.6', '1.10', '1.14'],
    'sub_norm_group_2': ['2.2', '2.6', '2.10', '2.14'],
    'sub_norm_group_3': ['3.2', '3.6', '3.10', '3.14']
}

for group_name, columns in groups.items():
    comparison_results[group_name] = data[columns].mean(axis=1)

In [12]:
comparison_results['%_sub_norm_gr_1_and_gr_2'] = round((comparison_results['sub_norm_group_2'] - comparison_results['sub_norm_group_1']) / comparison_results['sub_norm_group_1'] * 100, 2)
comparison_results['%_sub_norm_gr_1_and_gr_3'] = round((comparison_results['sub_norm_group_3'] - comparison_results['sub_norm_group_1']) / comparison_results['sub_norm_group_1'] * 100, 2)
comparison_results['%_sub_norm_gr_2_and_gr_3'] = round((comparison_results['sub_norm_group_3'] - comparison_results['sub_norm_group_2']) / comparison_results['sub_norm_group_2'] * 100, 2)

In [13]:
# Словарь с названиями групп и соответствующими столбцами
groups = {
    'beh_control_group_1': ['1.3', '1.9', '1.11', '1.12'],
    'beh_control_group_2': ['2.3', '2.9', '2.11', '2.12'],
    'beh_control_group_3': ['3.3', '3.9', '3.11', '3.12']
}

# Вычисление средних значений для каждой группы
for group_name, columns in groups.items():
    comparison_results[group_name] = data[columns].mean(axis=1)

In [14]:
comparison_results['%_beh_control_gr_1_and_gr_2'] = round((comparison_results['beh_control_group_2'] - comparison_results['beh_control_group_1']) / comparison_results['beh_control_group_1'] * 100, 2)
comparison_results['%_beh_control_gr_1_and_gr_3'] = round((comparison_results['beh_control_group_3'] - comparison_results['beh_control_group_1']) / comparison_results['beh_control_group_1'] * 100, 2)
comparison_results['%_beh_control_gr_2_and_gr_3'] = round((comparison_results['beh_control_group_3'] - comparison_results['beh_control_group_2']) / comparison_results['beh_control_group_2'] * 100, 2)

In [15]:
# Словарь с названиями групп и соответствующими столбцами
cognitive_groups = {
    'cognitive_group_1': ['1.4', '1.13', '1.15', '1.16'],
    'cognitive_group_2': ['2.4', '2.13', '2.15', '2.16'],
    'cognitive_group_3': ['3.4', '3.13', '3.15', '3.16']
}

# Вычисление средних значений для каждой группы
for group_name, columns in cognitive_groups.items():
    comparison_results[group_name] = data[columns].mean(axis=1)

In [16]:
comparison_results['%_cognitive_gr_1_and_gr_2'] = round((comparison_results['cognitive_group_2'] - comparison_results['cognitive_group_1']) / comparison_results['cognitive_group_1'] * 100, 2)
comparison_results['%_cognitive_gr_1_and_gr_3'] = round((comparison_results['cognitive_group_3'] - comparison_results['cognitive_group_1']) / comparison_results['cognitive_group_1'] * 100, 2)
comparison_results['%_cognitive_gr_2_and_gr_3'] = round((comparison_results['cognitive_group_3'] - comparison_results['cognitive_group_2']) / comparison_results['cognitive_group_2'] * 100, 2)

In [17]:
comparison_results

,mean_group_1,mean_group_2,mean_group_3,%_mean_gr_1_and_gr_2,%_mean_gr_2_and_gr_3,%_mean_gr_1_and_gr_3,behavior_group_1,behavior_group_2,behavior_group_3,%_behavior_gr_1_and_gr_2,...,beh_control_group_3,%_beh_control_gr_1_and_gr_2,%_beh_control_gr_1_and_gr_3,%_beh_control_gr_2_and_gr_3,cognitive_group_1,cognitive_group_2,cognitive_group_3,%_cognitive_gr_1_and_gr_2,%_cognitive_gr_1_and_gr_3,%_cognitive_gr_2_and_gr_3
0,5.60,5.13,5.73,-8.39,11.70,2.32,7.00,6.67,7.00,-4.71,...,6.00,0.00,9.09,9.09,4.75,4.00,3.25,-15.79,-31.58,-18.75
1,4.73,5.07,5.07,7.19,0.00,7.19,4.33,6.33,6.67,46.19,...,5.50,5.26,15.79,10.00,3.75,2.75,1.75,-26.67,-53.33,-36.36
2,4.60,4.60,5.29,0.00,15.00,15.00,5.67,5.33,6.33,-6.00,...,6.25,16.67,38.89,19.05,5.00,4.50,5.00,-10.00,0.00,11.11
3,4.47,NaN,4.20,NaN,NaN,-6.04,5.67,NaN,3.67,NaN,...,3.50,NaN,-22.22,NaN,3.00,NaN,4.75,NaN,58.33,NaN
4,4.20,5.60,NaN,33.33,NaN,NaN,3.33,7.00,NaN,110.21,...,NaN,25.00,NaN,NaN,3.50,3.75,NaN,7.14,NaN,NaN
5,4.67,4.67,5.13,0.00,9.85,9.85,2.33,3.00,5.00,28.76,...,5.25,-11.54,-19.23,-8.70,4.50,5.00,5.25,11.11,16.67,5.00
6,4.20,4.93,4.80,17.38,-2.64,14.29,2.33,6.00,4.67,157.51,...,5.75,50.00,64.29,9.52,6.00,4.25,4.25,-29.17,-29.17,0.00
7,4.73,5.27,5.47,11.42,3.80,15.64,6.00,6.00,7.00,0.00,...,5.00,20.00,33.33,11.11,5.50,5.75,5.50,4.55,0.00,-4.35
8,NaN,5.67,NaN,NaN,NaN,NaN,NaN,7.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.50,NaN,NaN,NaN,NaN
9,5.27,5.47,4.60,3.80,-15.90,-12.71,5.00,7.00,7.00,40.00,...,6.00,-12.00,-4.00,9.09,3.00,3.75,2.00,25.00,-33.33,-46.67
10,3.33,4.40,4.33,32.13,-1.59,30.03,3.67,4.67,5.00,27.25,...,4.50,40.00,80.00,28.57,4.00,4.50,4.25,12.50,6.25,-5.56
11,4.80,4.67,4.60,-2.71,-1.50,-4.17,5.33,4.67,3.33,-12.38,...,4.50,28.57,28.57,0.00,6.50,6.50,6.00,0.00,-7.69,-7.69
12,5.00,5.53,5.27,10.60,-4.70,5.40,6.33,6.67,6.67,5.37,...,5.50,9.52,4.76,-4.35,5.00,5.25,5.00,5.00,0.00,-4.76
13,4.80,NaN,5.07,NaN,NaN,5.63,6.00,NaN,5.33,NaN,...,5.00,NaN,0.00,NaN,4.75,NaN,5.75,NaN,21.05,NaN
14,4.33,4.53,4.73,4.62,4.42,9.24,4.67,6.00,6.67,28.48,...,5.75,-5.88,35.29,43.75,4.25,4.75,2.75,11.76,-35.29,-42.11
15,3.67,4.67,4.47,27.25,-4.28,21.80,5.67,3.67,4.67,-35.27,...,5.25,133.33,133.33,0.00,2.50,4.50,3.75,80.00,50.00,-16.67

In [18]:
comparison_results.to_excel('_experiments_.xlsx')

In [41]:
mean_all_gr_1 =  group_1.dropna().to_numpy().mean()
mean_all_gr_1

np.float64(4.56)

In [42]:
mean_all_gr_2 =  group_2.dropna().to_numpy().mean()
mean_all_gr_2

np.float64(5.014285714285714)

In [43]:
mean_all_gr_3 =  group_3.dropna().to_numpy().mean()
mean_all_gr_3

np.float64(4.8820512820512825)

In [44]:
(mean_all_gr_2 - mean_all_gr_1) / mean_all_gr_1 * 100

np.float64(9.962406015037601)

In [45]:
(mean_all_gr_3 - mean_all_gr_1) / mean_all_gr_1 * 100

np.float64(7.062528115159712)

In [46]:
(mean_all_gr_3 - mean_all_gr_2) / mean_all_gr_2 * 100

np.float64(-2.637153919205192)

In [23]:
comparison_results

,mean_group_1,mean_group_2,mean_group_3,%_mean_gr_1_and_gr_2,%_mean_gr_2_and_gr_3,%_mean_gr_1_and_gr_3,behavior_group_1,behavior_group_2,behavior_group_3,%_behavior_gr_1_and_gr_2,...,%_beh_control_gr_1_and_gr_2,%_beh_control_gr_1_and_gr_3,%_beh_control_gr_2_and_gr_3,cognitive_group_1,cognitive_group_2,cognitive_group_3,%_cognitive_gr_1_and_gr_2,%_cognitive_gr_1_and_gr_3,%_cognitive_gr_2_and_gr_3,mean_all
0,5.60,5.13,5.73,-8.39,11.70,2.32,7.00,6.67,7.00,-4.71,...,0.00,9.09,9.09,4.75,4.00,3.25,-15.79,-31.58,-18.75,NaN
1,4.73,5.07,5.07,7.19,0.00,7.19,4.33,6.33,6.67,46.19,...,5.26,15.79,10.00,3.75,2.75,1.75,-26.67,-53.33,-36.36,NaN
2,4.60,4.60,5.29,0.00,15.00,15.00,5.67,5.33,6.33,-6.00,...,16.67,38.89,19.05,5.00,4.50,5.00,-10.00,0.00,11.11,NaN
3,4.47,NaN,4.20,NaN,NaN,-6.04,5.67,NaN,3.67,NaN,...,NaN,-22.22,NaN,3.00,NaN,4.75,NaN,58.33,NaN,NaN
4,4.20,5.60,NaN,33.33,NaN,NaN,3.33,7.00,NaN,110.21,...,25.00,NaN,NaN,3.50,3.75,NaN,7.14,NaN,NaN,NaN
5,4.67,4.67,5.13,0.00,9.85,9.85,2.33,3.00,5.00,28.76,...,-11.54,-19.23,-8.70,4.50,5.00,5.25,11.11,16.67,5.00,NaN
6,4.20,4.93,4.80,17.38,-2.64,14.29,2.33,6.00,4.67,157.51,...,50.00,64.29,9.52,6.00,4.25,4.25,-29.17,-29.17,0.00,NaN
7,4.73,5.27,5.47,11.42,3.80,15.64,6.00,6.00,7.00,0.00,...,20.00,33.33,11.11,5.50,5.75,5.50,4.55,0.00,-4.35,NaN
8,NaN,5.67,NaN,NaN,NaN,NaN,NaN,7.00,NaN,NaN,...,NaN,NaN,NaN,NaN,5.50,NaN,NaN,NaN,NaN,NaN
9,5.27,5.47,4.60,3.80,-15.90,-12.71,5.00,7.00,7.00,40.00,...,-12.00,-4.00,9.09,3.00,3.75,2.00,25.00,-33.33,-46.67,NaN
10,3.33,4.40,4.33,32.13,-1.59,30.03,3.67,4.67,5.00,27.25,...,40.00,80.00,28.57,4.00,4.50,4.25,12.50,6.25,-5.56,NaN
11,4.80,4.67,4.60,-2.71,-1.50,-4.17,5.33,4.67,3.33,-12.38,...,28.57,28.57,0.00,6.50,6.50,6.00,0.00,-7.69,-7.69,NaN
12,5.00,5.53,5.27,10.60,-4.70,5.40,6.33,6.67,6.67,5.37,...,9.52,4.76,-4.35,5.00,5.25,5.00,5.00,0.00,-4.76,NaN
13,4.80,NaN,5.07,NaN,NaN,5.63,6.00,NaN,5.33,NaN,...,NaN,0.00,NaN,4.75,NaN,5.75,NaN,21.05,NaN,NaN
14,4.33,4.53,4.73,4.62,4.42,9.24,4.67,6.00,6.67,28.48,...,-5.88,35.29,43.75,4.25,4.75,2.75,11.76,-35.29,-42.11,NaN
15,3.67,4.67,4.47,27.25,-4.28,21.80,5.67,3.67,4.67,-35.27,...,133.33,133.33,0.00,2.50,4.50,3.75,80.00,50.00,-16.67,NaN